# pip install pre-commit
# pre-commit install
# pre-commit run --all-files

minimum_pre_commit_version: 3.4.0
default_install_hook_types: [pre-commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
        stages: [pre-commit]
    -   id: check-toml
        stages: [pre-commit]
    -   id: end-of-file-fixer
        types: [python, toml]
        stages: [pre-commit]
    -   id: trailing-whitespace
        stages: [pre-commit]
    -   id: check-case-conflict
        stages: [pre-commit]
    -   id: mixed-line-ending
        args: ['--fix', 'auto']
        exclude: ^.*\.txt$
        stages: [pre-commit]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
        stages: [pre-commit]
      - id: python-use-type-annotations
        stages: [pre-commit]
      - id: text-unicode-replacement-char
        stages: [pre-commit]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.4'
    hooks:
      - id: ruff
        name: ruff - lint python code
        args: [--fix, --exit-non-zero-on-fix, --show-fixes, --config, .ruff.toml]
        stages: [pre-commit]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.4'
    hooks:
      - id: ruff-format
        name: ruff-format - format python code
        stages: [pre-commit]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.6.1'
    hooks:
    -   id: mypy
        name: mypy - static type checker
        args: [--config-file, pyproject.toml]
        stages: [pre-commit]
